'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AdvAdHocEndpointSoap", [Namespace]:="http://tempuri.org"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(xml)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SqlParameter()))>  _
    Partial Public Class AdvAdHocEndpoint
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private sqlbatchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication2.My.MySettings.Default.WindowsApplication2_localhost_AdvAdHocEndpoint
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event sqlbatchCompleted As sqlbatchCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/sqlserver/2004/SOAPsqlbatch", RequestNamespace:="http://schemas.microsoft.com/sqlserver/2004/SOAP", ResponseNamespace:="http://schemas.microsoft.com/sqlserver/2004/SOAP", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function sqlbatch(ByVal BatchCommands As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter", IsNullable:=false)> ByRef Parameters() As SqlParameter) As <System.Xml.Serialization.XmlArrayItemAttribute(GetType(SqlMessage), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false), System.Xml.Serialization.XmlArrayItemAttribute("SqlResultCode", GetType(Integer), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false), System.Xml.Serialization.XmlArrayItemAttribute(GetType(SqlRowCount), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false), System.Xml.Serialization.XmlArrayItemAttribute("SqlRowSet", GetType(System.Data.DataSet), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false), System.Xml.Serialization.XmlArrayItemAttribute(GetType(SqlTransaction), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false), System.Xml.Serialization.XmlArrayItemAttribute("SqlXml", GetType(System.Xml.XmlNode), [Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable:=false)> Object()
            Dim results() As Object = Me.Invoke("sqlbatch", New Object() {BatchCommands, Parameters})
            Parameters = CType(results(1),SqlParameter())
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub sqlbatchAsync(ByVal BatchCommands As String, ByVal Parameters() As SqlParameter)
            Me.sqlbatchAsync(BatchCommands, Parameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sqlbatchAsync(ByVal BatchCommands As String, ByVal Parameters() As SqlParameter, ByVal userState As Object)
            If (Me.sqlbatchOperationCompleted Is Nothing) Then
                Me.sqlbatchOperationCompleted = AddressOf Me.OnsqlbatchOperationCompleted
            End If
            Me.InvokeAsync("sqlbatch", New Object() {BatchCommands, Parameters}, Me.sqlbatchOperationCompleted, userState)
        End Sub
        
        Private Sub OnsqlbatchOperationCompleted(ByVal arg As Object)
            If (Not (Me.sqlbatchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sqlbatchCompleted(Me, New sqlbatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter")>  _
    Partial Public Class SqlParameter
        
        Private valueField As Object
        
        Private nameField As String
        
        Private sqlDbTypeField As sqlDbTypeEnum
        
        Private directionField As ParameterDirection
        
        Private maxLengthField As Long
        
        Private precisionField As Byte
        
        Private scaleField As Byte
        
        Private clrTypeNameField As String
        
        Private sqlCompareOptionsField() As sqlCompareOptionsEnum
        
        Private localeIdField As Integer
        
        Private sqlCollationVersionField As Integer
        
        Private sqlSortIdField As Integer
        
        Private xmlSchemaCollectionField As String
        
        Public Sub New()
            MyBase.New
            Me.sqlDbTypeField = sqlDbTypeEnum.NVarChar
            Me.directionField = ParameterDirection.Input
            Me.maxLengthField = CType(1,Long)
            Me.precisionField = CType(18,Byte)
            Me.scaleField = CType(0,Byte)
            Me.clrTypeNameField = ""
            Me.sqlCompareOptionsField = New sqlCompareOptionsEnum() {sqlCompareOptionsEnum.[Default]}
            Me.localeIdField = -1
            Me.sqlCollationVersionField = 0
            Me.sqlSortIdField = 0
            Me.xmlSchemaCollectionField = ""
        End Sub
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(sqlDbTypeEnum.NVarChar)>  _
        Public Property sqlDbType() As sqlDbTypeEnum
            Get
                Return Me.sqlDbTypeField
            End Get
            Set
                Me.sqlDbTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(ParameterDirection.Input)>  _
        Public Property direction() As ParameterDirection
            Get
                Return Me.directionField
            End Get
            Set
                Me.directionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(GetType(Long), "1")>  _
        Public Property maxLength() As Long
            Get
                Return Me.maxLengthField
            End Get
            Set
                Me.maxLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(GetType(Byte), "18")>  _
        Public Property precision() As Byte
            Get
                Return Me.precisionField
            End Get
            Set
                Me.precisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(GetType(Byte), "0")>  _
        Public Property scale() As Byte
            Get
                Return Me.scaleField
            End Get
            Set
                Me.scaleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute("")>  _
        Public Property clrTypeName() As String
            Get
                Return Me.clrTypeNameField
            End Get
            Set
                Me.clrTypeNameField = value
            End Set
        End Property
        
        'CODEGEN Warning: DefaultValue attribute on members of type sqlCompareOptionsEnum[] is not supported in this version of the .Net Framework.
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property sqlCompareOptions() As sqlCompareOptionsEnum()
            Get
                Return Me.sqlCompareOptionsField
            End Get
            Set
                Me.sqlCompareOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(-1)>  _
        Public Property localeId() As Integer
            Get
                Return Me.localeIdField
            End Get
            Set
                Me.localeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(0)>  _
        Public Property sqlCollationVersion() As Integer
            Get
                Return Me.sqlCollationVersionField
            End Get
            Set
                Me.sqlCollationVersionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute(0)>  _
        Public Property sqlSortId() As Integer
            Get
                Return Me.sqlSortIdField
            End Get
            Set
                Me.sqlSortIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(),  _
         System.ComponentModel.DefaultValueAttribute("")>  _
        Public Property xmlSchemaCollection() As String
            Get
                Return Me.xmlSchemaCollectionField
            End Get
            Set
                Me.xmlSchemaCollectionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/sqltypes")>  _
    Partial Public Class xml
        
        Private anyField() As System.Xml.XmlNode
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlTransaction")>  _
    Partial Public Class SqlTransaction
        
        Private descriptorField() As Byte
        
        Private typeField As SqlTransactionType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Descriptor() As Byte()
            Get
                Return Me.descriptorField
            End Get
            Set
                Me.descriptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As SqlTransactionType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Public Enum SqlTransactionType
        
        '''<remarks/>
        Begin
        
        '''<remarks/>
        Commit
        
        '''<remarks/>
        Rollback
        
        '''<remarks/>
        EnlistDTC
        
        '''<remarks/>
        Defect
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlRowCount")>  _
    Partial Public Class SqlRowCount
        
        Private countField As Long
        
        '''<remarks/>
        Public Property Count() As Long
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlMessage")>  _
    Partial Public Class SqlMessage
        
        Private classField As Integer
        
        Private lineNumberField As Integer
        
        Private messageField As String
        
        Private numberField As Integer
        
        Private procedureField As String
        
        Private serverField As String
        
        Private sourceField As String
        
        Private stateField As Integer
        
        '''<remarks/>
        Public Property [Class]() As Integer
            Get
                Return Me.classField
            End Get
            Set
                Me.classField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LineNumber() As Integer
            Get
                Return Me.lineNumberField
            End Get
            Set
                Me.lineNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Number() As Integer
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Procedure() As String
            Get
                Return Me.procedureField
            End Get
            Set
                Me.procedureField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Server() As String
            Get
                Return Me.serverField
            End Get
            Set
                Me.serverField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As Integer
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/sqltypes")>  _
    Public Enum sqlDbTypeEnum
        
        '''<remarks/>
        BigInt
        
        '''<remarks/>
        Binary
        
        '''<remarks/>
        Bit
        
        '''<remarks/>
        [Char]
        
        '''<remarks/>
        DateTime
        
        '''<remarks/>
        [Decimal]
        
        '''<remarks/>
        Float
        
        '''<remarks/>
        Image
        
        '''<remarks/>
        Int
        
        '''<remarks/>
        Money
        
        '''<remarks/>
        NChar
        
        '''<remarks/>
        NText
        
        '''<remarks/>
        NVarChar
        
        '''<remarks/>
        Real
        
        '''<remarks/>
        SmallDateTime
        
        '''<remarks/>
        SmallInt
        
        '''<remarks/>
        SmallMoney
        
        '''<remarks/>
        Text
        
        '''<remarks/>
        Timestamp
        
        '''<remarks/>
        TinyInt
        
        '''<remarks/>
        Udt
        
        '''<remarks/>
        UniqueIdentifier
        
        '''<remarks/>
        VarBinary
        
        '''<remarks/>
        VarChar
        
        '''<remarks/>
        [Variant]
        
        '''<remarks/>
        Xml
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter")>  _
    Public Enum ParameterDirection
        
        '''<remarks/>
        Input
        
        '''<remarks/>
        InputOutput
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/sqlserver/2004/sqltypes")>  _
    Public Enum sqlCompareOptionsEnum
        
        '''<remarks/>
        [Default]
        
        '''<remarks/>
        None
        
        '''<remarks/>
        IgnoreCase
        
        '''<remarks/>
        IgnoreNonSpace
        
        '''<remarks/>
        IgnoreKanaType
        
        '''<remarks/>
        IgnoreWidth
        
        '''<remarks/>
        BinarySort
        
        '''<remarks/>
        BinarySort2
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub sqlbatchCompletedEventHandler(ByVal sender As Object, ByVal e As sqlbatchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sqlbatchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property Parameters() As SqlParameter()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),SqlParameter())
            End Get
        End Property
    End Class
End Namespace
