'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Data.SqlTypes
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AdvSalesEndpointSoap", [Namespace]:="http://tempuri.org")>  _
    Partial Public Class AdvSalesEndpoint
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetSalesPersonSalesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSalesTotalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSalespersonListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Apress.Samples.My.MySettings.Default.WindowsApplication1_localhost_AdvSalesEndpoint
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetSalesPersonSalesCompleted As GetSalesPersonSalesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSalesTotalCompleted As GetSalesTotalCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSalespersonListCompleted As GetSalespersonListCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalesPersonSales", RequestNamespace:="http://tempuri.org", ResponseNamespace:="http://tempuri.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSalesPersonSales(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal SalespersonID As System.Data.SqlTypes.SqlInt32) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetSalesPersonSales", New Object() {SalespersonID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSalesPersonSalesAsync(ByVal SalespersonID As System.Data.SqlTypes.SqlInt32)
            Me.GetSalesPersonSalesAsync(SalespersonID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSalesPersonSalesAsync(ByVal SalespersonID As System.Data.SqlTypes.SqlInt32, ByVal userState As Object)
            If (Me.GetSalesPersonSalesOperationCompleted Is Nothing) Then
                Me.GetSalesPersonSalesOperationCompleted = AddressOf Me.OnGetSalesPersonSalesOperationCompleted
            End If
            Me.InvokeAsync("GetSalesPersonSales", New Object() {SalespersonID}, Me.GetSalesPersonSalesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSalesPersonSalesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSalesPersonSalesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSalesPersonSalesCompleted(Me, New GetSalesPersonSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalesTotal", RequestNamespace:="http://tempuri.org", ResponseNamespace:="http://tempuri.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSalesTotal(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal SalespersonID As System.Data.SqlTypes.SqlInt32) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> System.Data.SqlTypes.SqlMoney
            Dim results() As Object = Me.Invoke("GetSalesTotal", New Object() {SalespersonID})
            Return CType(results(0),System.Data.SqlTypes.SqlMoney)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSalesTotalAsync(ByVal SalespersonID As System.Data.SqlTypes.SqlInt32)
            Me.GetSalesTotalAsync(SalespersonID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSalesTotalAsync(ByVal SalespersonID As System.Data.SqlTypes.SqlInt32, ByVal userState As Object)
            If (Me.GetSalesTotalOperationCompleted Is Nothing) Then
                Me.GetSalesTotalOperationCompleted = AddressOf Me.OnGetSalesTotalOperationCompleted
            End If
            Me.InvokeAsync("GetSalesTotal", New Object() {SalespersonID}, Me.GetSalesTotalOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSalesTotalOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSalesTotalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSalesTotalCompleted(Me, New GetSalesTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalespersonList", RequestNamespace:="http://tempuri.org", ResponseNamespace:="http://tempuri.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSalespersonList() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetSalespersonList", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSalespersonListAsync()
            Me.GetSalespersonListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSalespersonListAsync(ByVal userState As Object)
            If (Me.GetSalespersonListOperationCompleted Is Nothing) Then
                Me.GetSalespersonListOperationCompleted = AddressOf Me.OnGetSalespersonListOperationCompleted
            End If
            Me.InvokeAsync("GetSalespersonList", New Object(-1) {}, Me.GetSalespersonListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSalespersonListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSalespersonListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSalespersonListCompleted(Me, New GetSalespersonListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetSalesPersonSalesCompletedEventHandler(ByVal sender As Object, ByVal e As GetSalesPersonSalesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSalesPersonSalesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetSalesTotalCompletedEventHandler(ByVal sender As Object, ByVal e As GetSalesTotalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSalesTotalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.SqlTypes.SqlMoney
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.SqlTypes.SqlMoney)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub GetSalespersonListCompletedEventHandler(ByVal sender As Object, ByVal e As GetSalespersonListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSalespersonListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
