//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace APress.Samples.localhost {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    using System.Data.SqlTypes;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdvSalesEndpointSoap", Namespace="http://tempuri.org")]
    public partial class AdvSalesEndpoint : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSalesPersonSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesTotalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalespersonListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdvSalesEndpoint() {
            this.Url = global::APress.Samples.Properties.Settings.Default.Listing16_5_localhost_AdvSalesEndpoint;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSalesPersonSalesCompletedEventHandler GetSalesPersonSalesCompleted;
        
        /// <remarks/>
        public event GetSalesTotalCompletedEventHandler GetSalesTotalCompleted;
        
        /// <remarks/>
        public event GetSalespersonListCompletedEventHandler GetSalespersonListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalesPersonSales", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSalesPersonSales([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlInt32 SalespersonID) {
            object[] results = this.Invoke("GetSalesPersonSales", new object[] {
                        SalespersonID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesPersonSalesAsync(System.Data.SqlTypes.SqlInt32 SalespersonID) {
            this.GetSalesPersonSalesAsync(SalespersonID, null);
        }
        
        /// <remarks/>
        public void GetSalesPersonSalesAsync(System.Data.SqlTypes.SqlInt32 SalespersonID, object userState) {
            if ((this.GetSalesPersonSalesOperationCompleted == null)) {
                this.GetSalesPersonSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesPersonSalesOperationCompleted);
            }
            this.InvokeAsync("GetSalesPersonSales", new object[] {
                        SalespersonID}, this.GetSalesPersonSalesOperationCompleted, userState);
        }
        
        private void OnGetSalesPersonSalesOperationCompleted(object arg) {
            if ((this.GetSalesPersonSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesPersonSalesCompleted(this, new GetSalesPersonSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalesTotal", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.SqlTypes.SqlMoney GetSalesTotal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlInt32 SalespersonID) {
            object[] results = this.Invoke("GetSalesTotal", new object[] {
                        SalespersonID});
            return ((System.Data.SqlTypes.SqlMoney)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesTotalAsync(System.Data.SqlTypes.SqlInt32 SalespersonID) {
            this.GetSalesTotalAsync(SalespersonID, null);
        }
        
        /// <remarks/>
        public void GetSalesTotalAsync(System.Data.SqlTypes.SqlInt32 SalespersonID, object userState) {
            if ((this.GetSalesTotalOperationCompleted == null)) {
                this.GetSalesTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesTotalOperationCompleted);
            }
            this.InvokeAsync("GetSalesTotal", new object[] {
                        SalespersonID}, this.GetSalesTotalOperationCompleted, userState);
        }
        
        private void OnGetSalesTotalOperationCompleted(object arg) {
            if ((this.GetSalesTotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesTotalCompleted(this, new GetSalesTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.orgGetSalespersonList", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSalespersonList() {
            object[] results = this.Invoke("GetSalespersonList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalespersonListAsync() {
            this.GetSalespersonListAsync(null);
        }
        
        /// <remarks/>
        public void GetSalespersonListAsync(object userState) {
            if ((this.GetSalespersonListOperationCompleted == null)) {
                this.GetSalespersonListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalespersonListOperationCompleted);
            }
            this.InvokeAsync("GetSalespersonList", new object[0], this.GetSalespersonListOperationCompleted, userState);
        }
        
        private void OnGetSalespersonListOperationCompleted(object arg) {
            if ((this.GetSalespersonListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalespersonListCompleted(this, new GetSalespersonListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSalesPersonSalesCompletedEventHandler(object sender, GetSalesPersonSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesPersonSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesPersonSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSalesTotalCompletedEventHandler(object sender, GetSalesTotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.SqlTypes.SqlMoney Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.SqlTypes.SqlMoney)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetSalespersonListCompletedEventHandler(object sender, GetSalespersonListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalespersonListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalespersonListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591